---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: talos-test
endpoint: "https://192.168.1.24:6443"

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: "v1.14.0-alpha.2"

# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.36.2

allowSchedulingOnControlPlanes: true

nodes:
  - hostname: master
    controlPlane: true
    ipAddress: 192.168.1.24
    installDisk: /dev/sda
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
    volumes:
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.dev_path == "/dev/sda"
          minSize: 40GiB
          maxSize: 50GiB

patches:
  - "@./patches/pod-security.yaml"

## LVM features still in beta = not yet supported by talhelper. Copy paste lvm.yaml inside rendered config for now
#   - "@./patches/lvm.yaml"