---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: home-ops
endpoint: "https://192.168.1.100:6443"

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: "v1.14.0-alpha.2"

# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.36.2

allowSchedulingOnControlPlanes: true

nodes:
  - hostname: master
    controlPlane: true
    ipAddress: 192.168.1.100
    installDisk: /dev/sda
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
    nameservers:
      - 192.168.1.50
      - 1.1.1.1
    volumes:
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.dev_path == "/dev/sda"
          minSize: 40GiB
          maxSize: 50GiB

patches:
  - "@./patches/disable-admission-control.yaml"
  - "@./patches/disable-coredns.yaml"
  - "@./patches/lvm.yaml"
  - "@./patches/master-network.yaml"
  - "@./patches/sysctls.yaml"