# /etc/pve/qemu-server/{VMID}.conf

balloon: 2048
boot: order=scsi0;ide2;net0
cores: 2
cpu: x86-64-v2-AES
ide2: local:iso/TrueNAS-SCALE-25.10.1.iso,media=cdrom,size=2097976K
memory: 4096
meta: creation-qemu=10.1.2,ctime=1767385221
name: truenas
net0: virtio=BC:24:11:63:41:7C,bridge=vmbr0,firewall=1
numa: 0
onboot: 1
ostype: l26
scsi0: local-lvm:vm-1000-disk-0,iothread=1,size=20G,ssd=1
scsi1: /dev/disk/by-id/ata-ST2000DM001-1CH164_Z1E6J3ZJ,size=1953514584K,serial=Z1E6J3ZJ
scsihw: virtio-scsi-single
smbios1: uuid=2dd1be1b-239b-4e14-8f75-6f92da84a1c9
sockets: 1
vmgenid: 48f87b3b-ecd0-4663-ad82-a1ca8086f527