apiVersion: v1
kind: Secret
metadata:
  name: bazarr-secret
type: Opaque
stringData:
  BAZARR__AUTH__APIKEY: ENC[AES256_GCM,data:lmwshv4ffqGhOBal6C0Go8fmGx8sOYdeEZLkmwhHO3g=,iv:vMQWFM5cMz+Zx4LyZ8Y/naHdqALokuggvquNMKaTmmA=,tag:8/d448Q++wRgzkkFu4aLZg==,type:str]
sops:
  age:
    - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ1VEVzVtUHZsbnNBU1l2
        V3RsRVVYZ0V4eC9xYVVFN1R0aDF2bHNUVUhvCnN6NDJFdzY3QldZb2pHaVpzaVp6
        YkdzVkFHZzk3S05mNHpXOXdPRC9RRUUKLS0tIEZOK21jbURCT2t0MFBSd3V0YW96
        dmJaWmo0TTBUTHdldDVKSzQyb2piZlEKXr3b9Es+v+9vmIyzZ5k/hZa1T/GMAhvZ
        g0lWPdCH1GzknMt/G5U/FB4OBifV4Ol6v2MeS5SRPhJ9uaQPn29hKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T23:39:30Z"
  mac: ENC[AES256_GCM,data:ql+NxC9AyyzCzyEnOJMztkC16UUsFH2YTxpyecqL/lx7r1jU1TTFqR5Gh6yUreK8b6adTlzlBcohdOBeLrteRwN+K2cmscNfVKvvv1SXYrKMU70QHF83Gon5jBzTzszhGys1Sfojrm/w3N98ZWfOo5DjYSLWJ2cbYpKqviN5g+o=,iv:Te3KtcO7UEkw7AMBjsS5s99cxBLJ5YJU+WOoHSEBb+8=,tag:HO10eSbVBQZsDuUSWRIiRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
