---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP}-postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: ${CNPG_REPLICAS:-1}
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-minimal-trixie
  postgresql:
    parameters:
      # lessen disk writes (default is 5min)
      archive_timeout: "30min"

  bootstrap:
    initdb:
      database: ${APP}
      owner: ${APP}

    ## comment initdb: and uncomment recovery: in order to restore to a previous state.
    # recovery:
    #   source: origin
    #   database: ${APP}
    #   owner: ${APP}
    #   recoveryTarget:
    #     targetTime: "2024-01-15T10:30:00Z"

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        # Backup Object Store (push, read-write)
        barmanObjectName: "${APP}-postgres-backup"

  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          # Recovery Object Store (pull, read-only)
          barmanObjectName: "${APP}-postgres-backup"
          serverName: "${APP}-postgres"

  storage:
    storageClass: ${CNPG_DATA_STORAGE_CLASS:-openebs-lvm}
    size: ${CNPG_DATA_STORAGE_SIZE:-4Gi}

  walStorage:
    storageClass: ${CNPG_WAL_STORAGE_CLASS:-openebs-lvm}
    size: ${CNPG_WAL_STORAGE_SIZE:-2Gi}

  resources:
    requests:
      cpu: ${CNPG_CPU_REQUEST:-100m}
      memory: ${CNPG_MEMORY_REQUEST:-128Mi}
    limits:
      memory: ${CNPG_MEMORY_LIMIT:-512Mi}
