apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-cnpg-backup
stringData:
    ENDPOINT_URL: ENC[AES256_GCM,data:pn46PJnW++pdtfW2KX4fquyj/2aODT88F8cCAVoI5nc=,iv:SKOuzsBSC77X8Yk9L6b3c4/3vZM8pemHKT6mQBsAjlw=,tag:hgMZV3rtM29rhWkZbwLDLQ==,type:str]
    ACCESS_KEY_ID: ENC[AES256_GCM,data:njrqhkHvSrHjnYTdL6a4v8u0sm0=,iv:OndHEiiJLkwo7Hf3zqVgjNjxvOT6nDsP2AG2t2gnSAg=,tag:8uHzMD4DAhCmdR6gLx0wLA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Dyb5i6O1XPgYE6hkzlp/0NsByj4fZiOjepUGQ7MnmI2cCjCUthnZww==,iv:iwykWwlwYal6tJLXEMO1Cb/+WxUJNPj6ZYYzslOf9hs=,tag:+AyhSg+snWod0ofH7A+6zA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUklWalBDSVFNNGlnSTZX
            U0FkdGZFY1IyYXVwWDBia1BES3JnZ0dSSFVBCjR3K2E4V3hZS1hWc1Uvdnh4NzFx
            T2V1M1ZIRkFYUGtEeFAvMFB6VTNMc2MKLS0tIElxWHlIN1pqK3VBdnhmQjBGS1Iw
            S0t1WW1hOEFLRUh2dWZMNWVUSG16U3cK5JhrqApEgS6E3WCArj/d3xzQU+Kvhmj1
            0DHFjDT3VS9mnTnZq1z/TMFimBQ50ZXQ2yyxBK0DrNNj89SXt45tSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T20:05:38Z"
    mac: ENC[AES256_GCM,data:GKKTlZ6igAXsoOr3vmcHQ/OgqTTQU/Xobd51G1gtbuGoowv9418hqZh8mBwvbzPiyFnDdB2Vdrqv+2lfxtlTExvYickDlOmaHuAk+SqWwPtpOFs+kLs2XPCgeupjskNi8FWkbqJIEbbN+48HZzjJSJ53ChyMqbNa+Fv5m02hakM=,iv:9XlIF4awT2unKUdHF2CLVhWtlZF5FnHs63eu/dU5XGY=,tag:/wkuBIFg85DUhEirsJn02g==,type:str]
    version: 3.13.2
