apiVersion: v1
metadata:
  name: db-encryption
  namespace: homarr
kind: Secret
type: Opaque
data:
  db-encryption-key: ENC[AES256_GCM,data:wuITYgMwtNaAQE1mO5RJUvLyX/8kMeVuJizXLmemb+OEx8XIzSBehvNUeEnz1EQTd05x4ipnI63v70BZoWHFPQ==,iv:HkTeTcsgI7rXTur4I9wFCd8k+TxKcesmxQFf8huphOQ=,tag:ZA1qIDi9FXTLrnj3UkfK9w==,type:str]
sops:
  age:
    - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyT3QwN2lTRkpYUHlhdmZO
        blpOQlpvQW52Q3ArZnY2NEFsSUx2SCtjZ0RjCnlJWjk5TytJSTFjYzU5azIxeGRx
        VmFTRTc4SUt1UG9xL0N1NzNwbklRMTQKLS0tIGRKVEpJVDR0RDFmUkJEWStLY3Qz
        bi9TSEJSejF3L2hTRTZiOEQ2U1pWR0UKJIU94hkH5NoYKmGnbxhPeC2QRS1pU3sj
        J/iMTxYvpANG5dX5twZzs4LCdCBsPwBnc6eBSFMRoYLTIbWyEdPmCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-03T07:30:22Z"
  mac: ENC[AES256_GCM,data:l644S7PoaLrOtL5NScyNqll637uZLpL9biCzUjNwm5LmcR5qdts8USznTKCguyyo3pbxphTZl+NCEnmbmRAv3pmHHj3LYgFlRqJU1p1COlfUoOiZN5OT84D/3170kvsqVWcAELsFst2djftK3f6MQkkNtG4mKbDHxjLC27/PeOU=,iv:mfYJ/pLjkTR4ZnTS2R11/Ha26Tj3jsTUwz1SOzmuOJ0=,tag:X308Ea8Bar4QoghopzqRhg==,type:str]
  encrypted_regex: ^(data|db-encryption-key)$
  version: 3.10.2
