apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: db-encryption
    namespace: homarr
stringData:
    db-encryption-key: ENC[AES256_GCM,data:yfiT87m6Z84eDvAlHbXg6fKoE7coUFnJP5B5K77+nVLWhtVvcRAMKm2dXmZ3mV+PyaqCbIozun0t+IFC5Bq/JA==,iv:do8jTWXGIDHiRanFxB8NpWHvdzNDVHtqnJ5b4/4bpsM=,tag:lh+CrBq0UfSFoTg3i7mbaQ==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiY2VzMi9MMGV0cGUyclFD
            Y0VUaWVoN2JQMVVKT1ZhUk5LS2ZGcGVPLzNZClhuS3hYSkcvQkNiL2YxZkxic3hu
            N2xEbDI2T0VFM25TN29DY0grdEhkWU0KLS0tIE9iUjV0SXpRbHRWUVdNWW9oRkNw
            MnF3R0sxa0FVVnJzTjN0T3NtR2Q1cWMKvHOns5JnbAee+gs9s1btwKaqplaTmcW2
            3QxTplLJPgAgEQIPJK9uf9YP2jnDfMUehaiR3YdIEjotPt78xI9cpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T02:51:56Z"
    mac: ENC[AES256_GCM,data:lPFwqJdFuEFbF0c9BpNLYMzjb8qJLy3Vr4Xh3scYZVETq1Ip7/A+5xELtyK20SNLhnDr1wtPtem6szBCXu9knQiMP5ZID4T7x0x56gQwup5xVG0ZlL2lQQfT22QPLbdsDA1Oilt+jUgScH1zYIuklPihKKNKdX34+n4YaScvbOU=,iv:rx8FR+O7eSzVWwgQsLvw79ibCdRGQ2ZyCm/9cMfge6o=,tag:PnD3oW4fTeAADMbUDHPu9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
