apiVersion: v1
metadata:
  name: db-encryption
  namespace: homarr
kind: Secret
type: Opaque
data:
  db-encryption-key: ENC[AES256_GCM,data:Ws6+uzBaeuZq/9Rb50qlMvbvZGn4lBMlyqduUg/3Wh/E6QM2SpZnQJ9gGg16SWYevm260jkdJ6880JZDEdQgOg==,iv:q/mdIalKKmXxfOXJTO7G+Y9P6te++4ThYAZy3vxFSTA=,tag:Ew4hxqq18OdUG8yIEAbM6Q==,type:str]
sops:
  age:
    - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscm92U0QvSW81RVYwL1pP
        d0lqdTZvTU9IM21EaCtqc0VESFhaSkp5L0RBCnZ5RDJ3N1VYU0ZxY2h1aUw1eGdQ
        cU9WY3hnVVB1VlQ0YjVYblhnZ2VwY0UKLS0tIFV1SkNoR3haUWtLR0x6RnVJbHh5
        N1dQam5zcyttZUtGYi9nU3FzNnF6elEKevWhUAFFm4cn+JRfAEY+XupKn04CHG1A
        UlehvYMp46yG7G/In/ttSoyJG4ivfmVXvz5MwpU+qVCFKfWiw+sBPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-03T05:22:23Z"
  mac: ENC[AES256_GCM,data:B1rburdOAC7GPBtftvisnx1kzrKskQbRGwe3zx8HJ7w6f8+38zb40C3ew+j2saNkmykBynxF43Z7+cQ3emhPgccnmUp61t39kg2yjZgrgZurwUKfMl6zvJgUsSCA/RoBf5Jon2w+Digsq1eYIY3lMC14lDxDUewmyQ1EFDRfdXc=,iv:oa1ijRAlLFJm0VyoueQ42PhUNR5sAqcyORIrtgQ0ZNk=,tag:o+BUMuhqmVj5LXYvjZLGdQ==,type:str]
  encrypted_regex: ^(data|db-encryption-key)$
  version: 3.10.2
