apiVersion: v1
metadata:
    name: db-encryption
    namespace: homarr
kind: Secret
type: Opaque
data:
    db-encryption-key: ENC[AES256_GCM,data:klLT/KfXuI2GXvvNlJY10/rr8CRZii+YsieEKidrpKU=,iv:/2ssTGZyfuJcQgcl8G/P0amjV8Knkjfuvi+oaJ0LHRw=,tag:xFHVyKTUY723bFuAx/eJLA==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZGhCUFZnbG41N2hZeTJy
            MGF2MHQ3bWRUY0dVbEpRWmRmQWN0MEVTNVZNCmxwbHZsWnF5SktBQ29kM2FTbTVP
            SldWdGxGekVzSHNlSytVcnRMdnhYZ2sKLS0tIGdkdjRSUUJRUDg2WjJQanNheEY5
            UDRiQ0hLYitTU0VZTytzRXFyMlptRXcKY0tJa+Moe9RS5oM4qYm9drAg87NHNG1M
            TLemaauuTAQlgFOMdRdGjOofjhN37jO6rnImmUXWwtmkqZRWhtUTng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T05:15:05Z"
    mac: ENC[AES256_GCM,data:LtScuNm3/R/UzlwsfY91rGKF/mtBouGIfnQwTT1Ud6tDOkvhQVItuk+vYj2lLhyruIqII1ERzF8hzTPLxKG5JmgAkObv6+JCBqEZbAuVy5ZCYV/yeR1XZr7s/ZdRvozjLcIF5tkMoQyJmgRCECMITpHIs1lTsHGsuYD9d4E3MFs=,iv:/RcauWSR3Xp4YC22bUdfEPLMQnvZWWasTjQ+Id9p/Cw=,tag:H4WEf+zZov68rVRGLDAOWQ==,type:str]
    encrypted_regex: ^(data|db-encryption-key)$
    version: 3.10.2
