---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: 12h
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: '8.x'
      sourceRef:
        kind: HelmRepository
        name: *app
      interval: 12h
  values:
    image:
      tag: stable-fpm-alpine
    nextcloud:
      host: nextcloud.lan.tablar.ovh
      username: admin
      password: admin
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.0.0.0/8',
              3 => '192.168.1.1'
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );
    persistence:
      enabled: true
      existingClaim: nextcloud-library
    nginx:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: "nextcloud-postgres:5432"
      database: *app
      user: *app
      password: *app
    # postgresql:
    #   enabled: true
    #   global:
    #     postgresql:
    #       auth:
    #         database: *app
    #         username: *app
    #         password: *app
    #   primary:
    #     persistence:
    #       enabled: true
    #       existingClaim: nextcloud-postgresql-data
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/affinity: cookie
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      host: nextcloud.lan.tablar.ovh
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - nextcloud.lan.tablar.ovh
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
