---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tablar-ovh
spec:
  secretName: wildcard-tablar-ovh-tls

  duration: 2160h # valid for 90 days
  renewBefore: 120h # renew 5 days before expiration

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  dnsNames:
    - ${DOMAIN}
    - "*.${DOMAIN}"

  usages:
    - digital signature
    - key encipherment
