apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-database
  namespace: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi