---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opencloud
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opencloud
spec:
  chartRef:
    kind: OCIRepository
    name: opencloud
  interval: 30m
  values:
    controllers:
      opencloud:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          opencloud:
            image:
              repository: docker.io/opencloudeu/opencloud-rolling
              tag: 6.1.0
            command:
              - "/bin/sh"
              - "-c"
              - "opencloud init || true; opencloud server"
            env:
              IDM_CREATE_DEMO_USERS: false
              IDM_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: default-auth-app
                    key: password
              OC_ENABLE_OCM: false
              OC_INSECURE: false
              OC_LOG_LEVEL: info
              OC_URL: https://kumo.${DOMAIN}
              PROXY_HTTP_ADDR: 0.0.0.0:9200
              PROXY_TLS: false
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1024Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    service:
      app:
        ports:
          http:
            port: &port 9200
    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          # proxy-body-size is set to 0 to remove the body limit on file uploads
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: kumo.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - hosts:
              - kumo.${DOMAIN}

    persistence:
      data:
        existingClaim: opencloud
        globalMounts:
          - path: /var/lib/opencloud
            subPath: data
          - path: /etc/opencloud
            subPath: config
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
