apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secrets
type: Opaque
stringData:
  OPENCLOUD_SERVICE_ACCOUNT_ID: ENC[AES256_GCM,data:fKMPP0hBjXf5afbz1HtDWwXpKUY6nDWKD85uA5OFbDQKIRr+,iv:MM6EuaIss6Vk4mrYpQvLHCp2raj5woJPb2Nc9dQ++Kg=,tag:clyrhKeAsk/2+lr2/hfpQQ==,type:str]
  OPENCLOUD_SERVICE_ACCOUNT_SECRET: ENC[AES256_GCM,data:CFW5DhieG3DEtx43agvGC54yEm2OZZhZstcN0EG+UzjsP4lViNs17v+8JQ5CA9nekGeB,iv:k/7hme20AJ71uD8mRBIYXE7RgOVFY/zUluqGqLeqN9I=,tag:ZWw4IY4kSqFqfDldV/b/kQ==,type:str]
sops:
  age:
    - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL0N2WStKV04veWN3cjBr
        UzJoaVhuYWk5MklUaWtJeVl1V1NUbzZESnpjCnV6dm52amtIbVJYQmpHeVkvSDVy
        U2FlUGZUUGhlb2NWN0V6eFdJdnhJSzQKLS0tIFE1d1VuTUlhTmZQNjJGU0FkY3Jl
        Y1A4QTA2UTBDY2NuU21KVUl4TmFQYUkKyLH6jkS8DXIKMTfDBAUSovLo7oJRck8d
        2K27ZMMKdgr90yy9ZzHjYdC+f0Jkmbl7xAqk4HicSeQ+igQ52vk6eg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-25T19:16:38Z"
  mac: ENC[AES256_GCM,data:Vswf0qYTe+iYCZgQglRuPUEELNeyZ3cdR+aEhZU+wSzB462/S5/nHSIh+5LlLEWwzqEp2HIhNW2jcfp+m6svqwzaOxyJZeWxr9ds4G1z/eZPN/UB932HYwIlEAVx5OKo4ekJcmb8fr2NFA89FtPazR73ERrO+QnthJrNl7ZJlLk=,iv:6I2qxzE38+nSFC7HfkAsybvwdadSmYJc8aylKUCyB+M=,tag:sh1g+XZ1gQ0TJyTZUwHdsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
