apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-postgres-auth
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:D//2Pee96bc=,iv:4a2wV387Av5YcmcgkQEKhNsxuV1YfQVJcK9KuqnKnBM=,tag:dvKU0GxoVNXDbcz2NomGgQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:oTba5DAu4TA=,iv:GJVTJFPZnx1zQFXKf2TjVK6uUH1bdieWfufLSFXXeI8=,tag:lzr6leJdgJ0Fd1o5wXcP3g==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT1NTUi8vYmV5Vjcwbldm
            emNrOTZwYm8rWTdvL2c2cjYrM0tKUmIwNjNFClZPcGVSNXpRRVc5bzlCSHhkTU1v
            SnRoNjNjTmJaUGlHaVM0MTRUclAvNHMKLS0tIExDY3hSQjV3ZEZ1QUxOcDAyTFho
            RlFrVjhUNmMvWFdpcTVINGlYSXIvNW8KtVCJGpUJEeg/xQ3CDChjzjRG+nvjq6oZ
            H7xbJF/33tdsz1PDy+g++o8py65pFVDUny3WRwvDDD/TRBg+1Hg4wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T22:37:53Z"
    mac: ENC[AES256_GCM,data:F9TmrUBzmNbow6bHKrtUnHhSlRw6rwOjCSt72rHGqJsgqvp9TxlPLbYcuNrx9VsqqhQ+z76P5aoI5zeBzXCPqIm1m7La95LTg94GVxmz0WFjVlBYcraDmkI7m/eRHlPHUF1h2akHXHctCLP1rfB6GmUZw+6XxzmxNgoFszypmSk=,iv:nZB+lTCuJLxZDReA329JgiDaQbMBsCo9VRyVtnQ+6cg=,tag:wV76lpKkOsvNVCfbxZOMJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
