---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: &name backup-daily
spec:
  name: *name
  cron: "0 6 * * *" # every day at 6AM
  task: "backup"
  retain: 14
  concurrency: 1
  groups:
    - backup
  parameters:
    full-backup-interval: "7"
