---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: &name snapshot-6h
spec:
  name: *name
  cron: "0 */6 * * *" # every 6h
  task: "snapshot"
  retain: 8
  concurrency: 2
  groups:
    - backup
