---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: &name snapshot-cleanup
spec:
  name: *name
  cron: "0 4 * * *" # every day at 4AM
  task: snapshot-cleanup
  groups:
    - backup
