# cloud-config
package_update: true
package_upgrade: false
packages:
  - curl
  - qemu-guest-agent
  - nfs-common

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

locale: fr_FR
timezone: Europe/Paris

runcmd:
  - systemctl start qemu-guest-agent
  #  - curl -sfL https://get.k3s.io | sh -s - server --disable traefik --node-ip 10.0.1.1 --node-external-ip 192.168.1.100 --cluster-init # --node-label "storage=longhorn"
  - |
    curl -sfL https://get.k3s.io | sh -s - server \
      --cluster-init \
      --disable=traefik \
      --tls-san=192.168.1.100 \
      --write-kubeconfig-mode=644
  - chown ubuntu:ubuntu /etc/rancher/k3s/k3s.yaml
  - chown ubuntu:ubuntu /var/lib/rancher/k3s/server/node-token
