---
# Provides :
# LLDAP_JWT_SECRET
# LLDAP_KEY_SEED
# LLDAP_LDAP_BASE_DN
# LLDAP_LDAP_USER_PASS
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name lldap-secrets
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: *name
  dataFrom:
    - extract:
        key: "auth/lldap"
