apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# in this case, resources reside in a separate directory in order to make bootstrapping easier
resources:
  - ./certs/certificates.yaml
  - ./store/secret-store.yaml
