apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pihole-admin
  namespace: pihole
data:
  password: ENC[AES256_GCM,data:X2+914tv95iNi70cmCGfnA==,iv:LgFiWFvvn/7JOx3IJNbCufGie/YLpi1dgSiNrwDfdAU=,tag:tAOTQH0IsN92TRJRiXvfaA==,type:str]
sops:
  age:
    - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYjhtYnJYSTd1NFNxV2dv
        SEh6WmdydFgydnl0OXEyZlZ2U0RZeDFQUDE0CjkzbkxPdnZkNjlVb2JXNjZIMGlS
        N1EzSHJEdld3YjRHWXd1MzdLSU9GZXMKLS0tIHRCWlZTWVhJMHc4aU9VeUZKR0hL
        emZjMzVrSWRBcXkzdWg2eVg5bkl5T1UK3o8qHZMHvUhuSuTHgb4AhNxK+k/3LObK
        tqUWRr7Ck/bEJsZ0MyDGRguOM0J69yeOI8vWm/D9hDrWuh+HatYVpQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T15:45:09Z"
  mac: ENC[AES256_GCM,data:QRjWg+BSgNSHYFtPt0Z1SnQK5Tf/Bb9KQfHJEY/zmWKtHig3/B9+LIysAg4O/vAfylFwZ3p0zBChaPTMEAMCk+FOoaOjQnc8u8R6stGmA7Budz9+6RDNOqJ5rZZHmqJVaQ4NRPLWY51O3ztROEM4eI3M/Kv0dINIsEeFWaqqqro=,iv:o7Yv/MbGp2dNVLytNX0qITScIhjm+J6Vg0rdoQFUOmo=,tag:kzyjueuZRPaFKolEWvPbsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
