apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/apps/longhorn-system/snapshot-controller/app
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
