---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app discord-bot
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 1h
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  path: ./kubernetes/apps/default/discord-bot/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: discord-bot-postgres
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app discord-bot-postgres
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 1h
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  path: ./kubernetes/apps/default/discord-bot/db
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: volsync
      namespace: flux-system
    - name: postgres-operator
      namespace: flux-system
