apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: gitlab-registry-secret
  namespace: flux-system
data:
  .dockerconfigjson: ENC[AES256_GCM,data:hUeu/nbrkvT6aGUwqk6Z/bTn2LBHlOCIBbVFpwIBwYS9UD5EwWczfuvZ8901366H0dWOaEVzBjmTnFLRLmOVmiGIwGnl/7eqSeKLIvi8C8UDA9rpfbDeATsLG/CcxEx9OkEl1Y02+hxNWFrpdLoR0NJDgplHsQbBZ4rmPszAvDvwgVTFWVlAbw==,iv:8G3NTRXc4oD7MqYUPRBPPdimBJVTA4lmNw8Y4Azz4Ws=,tag:xdNxK+7oIXhjsSQy5uVBYA==,type:str]
sops:
  age:
    - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZUlac0pIQnM2dHdwTEN2
        dXF5TXFwcGc5bGp3eVpmSTV1ZzdNTndxdFNrCkJpVTZ5dVk0ZmhDUnZZV0YyZmgy
        cm94cU1lbXVIREpsZ3RxN21iblFwVDQKLS0tIEFsemFORENkOHlmbmJ5THRnVnZs
        T0ZaaUh4Qk5LYTNmbGt5U3Z1aGVPR1UKAcmQTPEp5SweytrQliO4xixqK3LPO1t0
        hNAek9Q3Isl5CXX3uduXktPX5WLCQR+UJRAd9lmgP2aFate2eu4wQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-24T15:40:03Z"
  mac: ENC[AES256_GCM,data:8hV5AOdRgnKRVoPQcPMdT/Nc3Lwn4WpfjOA7RSZE0IEs1hxgQ3rxEFpYpfse78S+xh3VDQCbePv5f+BbgD+EmiVQMD0yRidUCzZL0R0Q1l81/6l9J/IYLMu/Xuzz51dyKsM4sNUgnxfFywx0crKfjCrdS27VRw24nrWcaDQcvuk=,iv:lAGHBVvoL+YxdWhHyKzEJoMGjer+dZhBDnNa/lwoNtI=,tag:WOlOqVuCbTWAv1rjrZruEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
