apiVersion: v1
kind: Secret
metadata:
    name: discord-bot-secrets
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:NtlG4Rzto7ccTu0WfbHez4G08LkHE7BBei7TiLUAFwNBg5lqdDUvfJ4ePpy71yPb25wwN9MFg8CSWUsRZdGQTt2cpvlkJhZr,iv:k1fUEN2V5QYBCA9NsaslA5ehBosBFFJqnb5oUpcWWDg=,tag:C43RagJSlSW5yBAJO1gIZw==,type:str]
    HCLOUD_TOKEN: ENC[AES256_GCM,data:g6JSdxV/v30MJMo4QFjxN4D3k50bPd1jbAeLXTNB2VTFDcD9Aw99jPJapZqINBLgfes+Dww0XihhH7P2QsqqtQ==,iv:Ygn5dDc6JvbntQ9xGrQ2XaGSLw3XF5ANHbH51NaijzA=,tag:hE1Quv1cHyQhpD3I4Podjw==,type:str]
    RCLONE_B2_ACCOUNT: ENC[AES256_GCM,data:/tjUokSzUokXv8bCn2yFM6yUgHAorIKRqQ==,iv:Xfbx41SH+NfO9YZ3PK47PROIciVUVRzcNHwOr39mxOI=,tag:rLiXoS5T94XiMgGMcFlXIQ==,type:str]
    RCLONE_B2_KEY: ENC[AES256_GCM,data:rccAQ7KnxBlRUHLI99uJKydAjLKy0Pn8AxOXxF/kwQ==,iv:EsXMXtuRWpcA2JiyTnHXbFcYkqfMLkULoIkq3LymxBw=,tag:/xyyXNNM0PbgesnRP6GhpA==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncWZnUG1oRFJ1aGRMVHJJ
            NStMT0dTWkdpbDVmNEhlTnNFOVN2M2M1THhnCjB3ZzQ4OHRaVTYyMXkzK3hVdklD
            bTg4MkR1N0dMVGw4dGlpamZ4MjE2ek0KLS0tIFZXdXhlam83R0pVUHV3VlBQRFZE
            OHVSYS9BU01lejdMS2JpUkFCL1dCVUkKk49q0kacQXHiiSm9PAldD7Eal/z8VIRU
            EL0EA5tzHHisgMsLmUsi5adDpJHxC41Lm7mPqpd6W1FHm2d7szx6WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T00:21:41Z"
    mac: ENC[AES256_GCM,data:QV7HsT/ThBVT3bjFBvRi3VNa/GssO2RGfkAuhQxjUGhE15Eq0zBpcP6gvZJ4i228yXV5Egh6YSzDp8uWY6Pu+1PWmlHl4o5IxxENga6oJvmXF2VQtvjJY7Oc50BryOSz5ZvNr+n3mhEgftI2pDJvLITOCfwIrOzrE/wuCpB5pOw=,iv:MGkldQahFpicYcMe/hzXwDH9MQuc2YN2Pj8KbfrooeU=,tag:MjbGdjNNegVoMGGzXFdvwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
