apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-lvm
  resources:
    requests:
      storage: 10Gi
