---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-dst"
  labels:
    # The IfNotPresent policy instructs the controller to only apply the Kubernetes resources if they are not present on the cluster.
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${APP}-volsync-secret"
    copyMethod: Direct
    destinationPVC: "${VOLSYNC_PVC:=${APP}}"
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
      fsGroupChangePolicy: "OnRootMismatch"
    enableFileDeletion: true
    cleanupTempPVC: true
