apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jBM/nSTXQyhad/Hj4dyD4ZQuca3FvY+3SxpP6N4AbKTtT7VUn/+ehDwSvTcSafLI+9L8IITEwABDg76m0A==,iv:DbE/idHI5PHWtS0eoeSjovPrwUFOGcKLkv107PQFX0w=,tag:X4sNEA52yravVaIHIsDUlg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:TSbD6z3uRA==,iv:/shoZ+6kubptohTY4yLhmZ0k/l5x0DMsHy89W/heW2M=,tag:kb6YYbjkYOaNp6LVGsHUZw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2BNON1bSZWVXnJat0Vk7weJ/d50=,iv:eJkD0twQL2rW8w9oFpHF+FlX5vlOo/TxLvGkxBLmO64=,tag:u5fGM+V2Yhu7Kpte/peU1w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UfaGGaCb6KPOzLbuvpswBezJbvnFe+m6z4L6o1E5KAQ1jd59sTyiLQ==,iv:8kiAwMM91lo5cj3LQh+YFu5cGkZLOZCVyg/Kn7J1uNY=,tag://RgLYzkGFQLGAJNRYEfQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXplYVZZaGViVE85VmF5
            Z0gxVGdoVmhiVU9aMXJ4dTlVdVBsY095eGt3CjBCekFJYXhsVVNiTlVQL1NLNUt1
            K2tjSldjakk1eHRJSngzNU1hK1JkVTgKLS0tIDFBaEptUHk1NXBocU1xZ0k1cDR0
            WEJ0VlVMcmlPbXZ1Sm52ZWJjWjJ1ZUUKe1NfMwP8MqGudi9hGaBnmJCzdTQrGFZL
            Y7CIKcmjXCqlFEV/h0ANHhsWPxcCkx7XL5e4FfBOJZZjiPsRVNFLZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T17:37:03Z"
    mac: ENC[AES256_GCM,data:EeMwr86uzu5o9/0NWBxVMOdy4Kog/Mn9npsyAigSjq+0trFNiYGyBjboYEXnQ/+OtUhrPO/KsjbvHsrUAyRawZdTPTJkLKz/YsEKIsBD9sGECxSmQbHwHYrfIiVA9EQZDnYJLZN42yJtyc155XrA3dEoc0TAtYMNv/7mhjEp9mU=,iv:jQc7rtfeb9aAoF7USDHUhqfIGR1d7Y1L5Ft7EGmBAjY=,tag:saJmhUEZRLPGiCJi/m+LYg==,type:str]
    version: 3.13.2
