apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:E4JGuNndb/zhSLZIJDUb82iASZEdNeZ6xnosJUEM584EnuwHhqpwFPmJiPwYwDv3EUEdPfd69+JDPiuE9A==,iv:lStkFnOGwDmSzJflE+Kd4dUaoVf7o7zDa6NSPfqnEHc=,tag:CUJYVoUdpfpaCt1dhq844w==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:sTobrBTLGQ==,iv:dEzo+lndygrNJCU1SC951iSeJ/R7ByarHC9nbGO/O/4=,tag:cTFdY6EmYKcpWn+1XpKw+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdXN1KzVCazdkd29kYWR4
        amNJMnBOa2liNzJTREVVa0tkRHE4MzA5cGhzCnhzNHlrckI1YllYaG5TM05lRlRI
        VWpXWWRZQVY3S0lYckE1YVljU1lDYjgKLS0tIFpoZWM1cWMrQlVYbHhQMDg0TWJB
        OWVmQXNKWWlaeXJOVU9YYkx5THZzNjQKbX/8Cutl0zaSaovKStobM9x4Sd0hpTWD
        WAxz0ZndwX6m5RE+OOp/Bm/1DqE+SvT33JzPNR57voOcGNscwNk6+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T19:10:27Z"
  mac: ENC[AES256_GCM,data:9DddXF72nxqIpbWRF3Qcyq7zd3drHC7EJ5OB69RWyx8PuBnzed4uHp/UYBf3h/duaW5FTwo+u0uzcRb8Gj6z4oHPrBI9oHh5TKFOZFa1UNGbQcPaE61WYwkg1lqJ0k9ZFwIFZIHLkCml1SnBAN1IJ0HvLpySCuPeQJp9oMA31qo=,iv:jS7nNk3PKLj6rMQ0+GS31gO2mnsseOALd0CB0bl78zY=,tag:eGT2FfZ2C+5ZCDF53Jr/NQ==,type:str]
  version: 3.13.2
