apiVersion: v1
kind: Secret
metadata:
    name: ovh-credentials
    namespace: cert-manager
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7SBlzaXInA==,iv:ay0qU69NJ+CqsyWuMunv+52vHcEJ57CLZcROAsvaOxQ=,tag:GnVAYzQvYR0S4+cLJsAk2w==,type:comment]
    endpoint: ENC[AES256_GCM,data:uLGaBGChVS0nveB3,iv:N65KfppHDZ5Xd8vxCWnUK6/y5nguIT93o30Rn31s/X8=,tag:5RHTxZArzfYN62NO7yGURw==,type:str]
    #ENC[AES256_GCM,data:z2SsYChVQy/Tvu5Rxq9+RJ+B9LFusBf7CpMdCRxk/E+3iPYGy1BYKrUdHg2VLMlknQ==,iv:HnxiQHNekA5qfaZRQIpBpBJQL4mKTiyYmwf8ia1B6XQ=,tag:XHKoIWqhW7kp/A56qAMgWA==,type:comment]
    applicationKey: ENC[AES256_GCM,data:+mye6FhMhnoxERSvnjQG12RGaenx5Cn8,iv:eaoh/VQlmcvQ4EH/LAu1xmiDXPLxmZMNlSL9Ntyw0L0=,tag:7Clh8GcJFz68PEwJQmPrQA==,type:str]
    applicationSecret: ENC[AES256_GCM,data:Kwns5/3X9r4YOd1FtJ0V1YRuHrMDsB94a8ASHGqy+g4nmsljfRwOe4lFVeA=,iv:J8wLQWAvznB4ddcZbSHjYJPYwqT5J00a9VAmh067MpY=,tag:ebrmsd8/GkOtbXshvwecIQ==,type:str]
    consumerKey: ENC[AES256_GCM,data:xVoobWppkEaIXo7dUV1FbjezQ0CoYnGj7ja1Mb7aU8RPjHujO47QAsF+yHI=,iv:LyJndu7SlvrPzoGoUC7R7wL+ZdekIJTW3vtPzuFkYUI=,tag:eVxd0m1japd/Ykj1rji73A==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBET2IzdVZEWnNwL1VNYkJF
            alI5NDNYdGRSeVlSR2ZEL1pmaFRnTlBIUENBCiszRkdJcjUwZ2tXOEFEdXBYalp5
            MmVYcTZuUmkrNm03N09Nak1GQmxXMTQKLS0tIDZkZThZRVVhMUlpVSs2bUV4aVJk
            NUN0V2E5c25ZZkZFblBqRzdQU2V5VjAKAzHAaaFELQQu3nJjO0Azza+bSANUFPvJ
            lG1+MoKGH9lD+wNeEqYw3ETGUEMD7EDRA1zYW/6A3Q/XhxJlmyw4UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T19:46:33Z"
    mac: ENC[AES256_GCM,data:acQQG1MyPD15Xjvw1gcGS0QD3Tqmvr3Fqi5exBD78w73yqTFPwnlKyPTiI/SNr/JpU+CmwKgoehFFQmrqakUDT/CAstA2o2QYViUdGE+Dxx6KfFNKp7KH/+jFuVZzTddgST8w55wlKpC1KqoJmY/Zg+OaH715yKC8WAKZMTbmvk=,iv:lImNfTgkweZaD5S0zu9COBaBUMcyBexmA+re6Qql0rI=,tag:tn7XCdp25yu/v0Zdd30C+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
