---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-update-automation
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  wait: true
  targetNamespace: flux-system

  path: ./kubernetes/apps/flux-system/image-update-automation/app
  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn: []
