apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name servarr-oidc-secret
  namespace: multimedia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: *name
  data:
    - secretKey: client-secret
      remoteRef:
        key: "multimedia/oidc"
        property: client-secret
