apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: &name default-auth-app
spec:
  externalSecretName: *name

  namespaceSelectors:
    - matchLabels:
        app.kubernetes.io/part-of: apps

  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: 1m

  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: bitwarden-secretsmanager
      kind: ClusterSecretStore
    target:
      name: *name
    dataFrom:
      - extract:
          key: *name
