apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sonarr
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: infrastructure
      namespace: flux-system
  interval: 1h
  path: ./apps/multimedia/sonarr/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system 
    namespace: flux-system
  timeout: 15m
  targetNamespace: multimedia
  wait: false