---
machine:
  kernel:
    modules:
      - name: dm_thin_pool
      - name: dm_snapshot
      - name: dm_mirror

## LVM features still in beta = not yet supported by talhelper. Copy paste lvm.yaml inside rendered config for now
# ---
# apiVersion: v1alpha1
# kind: LVMVolumeGroupConfig
# name: vg0
# provisioning:
#   volumeSelector:
#     match: disk.dev_path == "/dev/sdb"
