---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-postgresql-init
  namespace: immich
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE EXTENSION IF NOT EXISTS cube;
    CREATE EXTENSION IF NOT EXISTS earthdistance;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-postgresql
  namespace: immich
spec:
  serviceName: immich-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgresql
  template:
    metadata:
      labels:
        app: immich-postgresql
    spec:
      containers:
      - name: immich-postgresql
        image: tensorchord/pgvecto-rs:pg16-v0.3.0
        env:
        - name: POSTGRES_USER
          value: immich
        - name: POSTGRES_PASSWORD
          value: immich
        - name: POSTGRES_DB
          value: immich
        # Store data in a subdir. Using a mount point directly as the data directory crashes the container
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: immich-postgresql
  namespace: immich
spec:
  selector:
    app: immich-postgresql
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None