apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-postgresql
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: "18.x"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-postgresql
  namespace: flux-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: bitnami-postgresql
    namespace: flux-system
  targetNamespace: immich
  install:
    createNamespace: true
  values:
    auth:
      username: immich
      password: immich
      database: immich
    
    primary:
      persistence:
        enabled: true
        size: 10Gi
        storageClass: local-path
      
      # PostgreSQL avec extensions pour Immich
      initdb:
        scripts:
          init.sql: |
            CREATE EXTENSION IF NOT EXISTS vectors;
            CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
    
    # Nom du service (pour se connecter depuis Immich)
    # immich-postgresql:5432