apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-auth
type: Opaque
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:LWe4UO3t,iv:fqb2cJyYbd15Ap1+cBSGxjvfBUlMWrqfxbssOAkVYZg=,tag:vgXvJDMMd4EyBT7PIQ7Uvw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:PXzdxavl,iv:fXKtVDd9e1vFZhET/Ieub+HcCw6MQzABF2WJNy7ZWig=,tag:cdLGB0jpqsWc2iyzfPxpZg==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:DF++yloV,iv:q7gv/dZTzD4W+C3Al68o7Pcs8LwqwAzw2aifrMvoI60=,tag:e2ME+c1PXboTAXkZbXibLQ==,type:str]
  DB_URL: ENC[AES256_GCM,data:HTi12NItb4ncoZRIb/6UO0ZxDp5kSe9H+DDgg518kII4/oyf4ma2I3UWCtznvF3txHt2RzJ1,iv:G3I2dWVbjGsgGMYoryGDn/AY5DWA0JBKO5J20VwMNRI=,tag:c095V/cp0giFUgoQR2eJcg==,type:str]
sops:
  age:
    - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMm0rTVdHeXpqakZYUFc3
        K3NHUHRnRWZvUU5aZE5PWkVWaXpOejRFU0NFCjlwVU5GZFk5UDNWR1dxdHJtU1Q4
        WC9lWndyTnhQMDNIaG1SUk5BMHNldmMKLS0tIGhuaU5MSXd4Vm8yNWhkempCTGd0
        QTJ0VXpNSkttQituZzZOMWU4dFY4VTQK9jtwHE19s15yRCAsvE2kasse/QiaydFc
        LaaE9VO2hc4Wacrag7Cg5Fxj60GN6V9PK81WW6LAei+p1q/uCCJdmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T18:08:33Z"
  mac: ENC[AES256_GCM,data:14NZHj5hBqtH270wgYnW32KXXZQ9mRdT2Wki30dPHY3tTPCGLEtRPwbGrHZI6IeDaKZPMYlfKEyvHIn39Ff4LzJRto9p+BFbvIRXj5dFdg9ru6lQtl51/UvJYVakbgO6UavMxK1CrCp3XXH95kFvy4sfmIsGjWQUxOrGYsP4DkQ=,iv:6dZeCCK1dqlG3oG1QbzkwwFPC5nODl4bJWVr1uqgoMs=,tag:3Y1ZOPBPWJbfTNyB7SlY0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
