---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
  recurringJobSelector: '[ { "name":"maintenance", "isGroup":true } ]'
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-backup
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
  recurringJobSelector: '[ { "name":"maintenance", "isGroup":true }, { "name":"backup", "isGroup":true } ]'
  encrypted: "false"
# ---
## encrypted volumes for S3
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: longhorn-backup-s3
# provisioner: driver.longhorn.io
# allowVolumeExpansion: true
# parameters:
#   numberOfReplicas: "3"
#   staleReplicaTimeout: "2880" # 48 hours in minutes
#   fromBackup: ""
#   fsType: "ext4"
#   recurringJobSelector: '[ { "name":"snapshot-6h", "isGroup":false }, { "name":"backup-daily", "isGroup":false } ]'
#   encrypted: "true"
#   # global secret that contains the encryption key that will be used for all volumes
#   csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
#   csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
#   csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
#   csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
#   csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
#   csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
#   csi.storage.k8s.io/node-expand-secret-name: "longhorn-crypto"
#   csi.storage.k8s.io/node-expand-secret-namespace: "longhorn-system"
