apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-postgres-init
data:
  init.sql: |
    BEGIN;
    ALTER DATABASE "sonarr-main" OWNER TO "sonarr";
    ALTER DATABASE "sonarr-log" OWNER TO "sonarr";
    COMMIT;
