apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-postgres
spec:
  volumeMode: Filesystem
  storageClassName: "nfs-csi-pgcluster"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
