apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: default
spec:
  containers:
    - name: main
      image: alpine:latest
      command:
        - /bin/sh
        - -c
        - sleep infinity
      resources: {}
  restartPolicy: Never
