apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-auth
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:HkuvL6IY,iv:3uX7hc0BA9Y+9FphvcaLbOb5ypeCw909rVbHy6zm+68=,tag:DHJ/shfeZmzyb/bqmq5PBA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:FkbAk//H,iv:Qk2lzVJBpecDgJkhzwz8vv7SmJQcb6C/I0o57izent4=,tag:RuCuxzJp3z8tddlBAUIKZw==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5blZXd3lKWStDNGduelph
            dW1QUGpGMWtPeUFrVDVmTkd6c1dldDYwbUJzClhydnBBWWlCSlFPMzhUdHFhaFBF
            bm13Z2tpcEdBR2lUWkt6K0xXM2xidUUKLS0tIFYzYWdDK2pSTkdWekdHRFpSZEJ5
            amFwM1YyNVptZEtYYkVMeXdSSUszQkUKuEEsw0p39tWH4//aDrAp1dCotDLTIuom
            1AoeAEK8Wz4qma4STB60u7olYvmB82AwbqWfB8Ql41nQkJ13VmzgJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T22:44:48Z"
    mac: ENC[AES256_GCM,data:x5t4LeE6t6WIxmKrkGQ4owYQABoev2XRdRwY0bUtHUoRdKZg13nIVEibViMlajrv6clU7QFe73qst2IHX5e/bQ3CDCl7zr0nEq0zVsvDREo943YxrsX6DRfpPKPWYGNRXiVe2FXQE4uK4F2yFdQMEQ/9ceriJc9Ceqixl4r8jS8=,iv:5y70byjETWhajbQ9RxnJoMccAvnxyvO7YuLCKCps4Ds=,tag:UJMaqD1IEAlc9zPdR783bg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
