apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-vpn-auth
type: Opaque
stringData:
    USERNAME: ENC[AES256_GCM,data:DFiOgV93jGmLldlkH5Z91gJ3XYz9IyGS,iv:b0GEl8ma8CqCMYzOkcTzeeP2V/jfYeO8AdCDC0F13Kc=,tag:mmZbE3na7COEzFcCbbY3XA==,type:str]
    PASSWORD: ENC[AES256_GCM,data:EIyhINSdsb1uuZIz7E+7u6F78/r3yOes,iv:x3MdIi3UeQAm0biuTNVEK7vop/K3Fh4nW5xlApmjg6w=,tag:Hy+2h7SyW6A5FEMeyusRGQ==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWkVIbTRJdTNmcHNLSUxn
            QzVOVHB4bmhxeDVGUFExSzRkNkw0YlB5OVE0CjlwZUg5RTgyUE9DdXlacTNFVjZi
            MU16ZG50VkRYSVY3Yk5QeUtMZFIxU1UKLS0tIG1ydTdPQmRyNFZqN1lFeVBpQjNy
            RXhmT1UzK29wZWR0L2FSN1FrM2RxQTgKVwW7vbcbzzuQ315Ucq7ac5bK8JZaXctT
            wfq2LxNjiHk4JC0D+S3Ytmg3qawUflT/3Arx4Tnvcdmc7ICZM4YMHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T20:43:18Z"
    mac: ENC[AES256_GCM,data:o2iEhLm1OxYO7oB+bnB92OeN8612wZFNAndG2h4/rwKQUS39vHdZXzWa871q0o7sr3/YrcIbjRx36syW3OZkToDgdFQh8qyMvhqzSPewd3j5sMMjx+0B4PDlFuFzMIg1lGe46KnQVNOHMcw3W8Mlsby/twzIxT0kTYs/9lfeHy4=,iv:ybuvSLA+VPpfLs/uvV+BTFjJNdkmpYFPjAz5pQkLIHs=,tag:i47Hq496ftsumcJKW09ePQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
