---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 15m
  prune: true
  wait: false
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  path: ./kubernetes/apps/default/immich/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: immich-postgres
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-postgres
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 15m
  prune: true
  wait: false
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  path: ./kubernetes/apps/default/immich/db
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: csi-driver-nfs
      namespace: flux-system

  decryption:
    provider: sops
