apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./database
  - ./external-secrets
  - ./flux-system
  - ./ingress-nginx
  - ./kube-system
  - ./monitoring
