apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: test-secret
    remoteRef:
      key: "4429562a-616d-4389-b756-b3df00178ca6"