# /etc/pve/qemu-server/{VMID}.conf

agent: 1
balloon: 2048
boot: order=scsi0;ide2;net0
cores: 1
cpu: x86-64-v2-AES
ide2: local:iso/OPNsense-25.7-dvd-amd64.iso,media=cdrom,size=2141198K
memory: 4096
meta: creation-qemu=10.0.2,ctime=1759937375
name: OPNSense
net0: virtio=BC:24:11:84:FA:2C,bridge=vmbr0,tag=20
net1: virtio=BC:24:11:38:CE:6C,bridge=vmbr0,tag=10
numa: 0
ostype: l26
scsi0: local-lvm:vm-100-disk-0,iothread=1,size=16G
scsihw: virtio-scsi-single
smbios1: uuid=fd8a2d2b-7438-4fff-920c-8cd1fcb53344
sockets: 1
vmgenid: 987f6741-6d1d-4957-a4ee-59976b05ee38
