# /etc/pve/qemu-server/{VMID}.conf

boot: order=scsi0
cicustom: vendor=local:snippets/ubuntu.yaml
ciuser: root
ide2: local-lvm:vm-9000-cloudinit,media=cdrom
ipconfig0: ip=dhcp
memory: 2048
meta: creation-qemu=10.0.2,ctime=1761217215
name: ubuntu24-cloudinit
net0: virtio=BC:24:11:FB:0F:02,bridge=vmbr0
scsi0: local-lvm:base-9000-disk-0,size=3584M
scsihw: virtio-scsi-pci
serial0: socket
smbios1: uuid=dd1cb35c-ecb5-49db-bff4-a4bc7416e85b
tags: cloudinit;noble;ubuntu-template
template: 1
vga: serial0
vmgenid: ec45a10e-b236-4755-a864-a4499754c03b
