apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  ref:
    semver: "79.x"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h
  timeout: 10m
  chartRef:
      kind: OCIRepository
      name: kube-prometheus-stack
      namespace: monitoring
  values:
    grafana:
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki-gateway.cluster.local
          access: proxy
          isDefault: false
          jsonData:
            httpHeaderName1: "X-Scope-OrgID"
          secureJsonData:
            httpHeaderValue1: "fake"
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.lan.tablar.ovh
        tls:
          - hosts:
              - grafana.lan.tablar.ovh

    alertmanager:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - alertmanager.lan.tablar.ovh
        tls:
          - hosts:
              - alertmanager.lan.tablar.ovh
    
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.lan.tablar.ovh
        tls:
          - hosts:
              - prometheus.lan.tablar.ovh
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        externalPrefixNilUsesHelmValues: false
        scrapeInterval: "120s"
        retention: 10d
        retentionSize: "9GiB"
        storageSpec:
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              storageClassName: nfs-csi
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
    
    # prometheusOperator:
    #   namespaces:
    #     releaseNamespace: true
    #     additional:
    #       - kube-system
    #       - immich