apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name discord-bot-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: *name
  dataFrom:
  - extract:
      key: "default/discord-bot"