---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: discord-bot
spec:
  interval: 12h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: discord-bot
spec:
  chartRef:
    kind: OCIRepository
    name: discord-bot
  interval: 1h
  timeout: 1h
  values:
    controllers:
      bot:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image:
              repository: registry.gitlab.com/tcordina/discord-bot
              tag: latest
              digest: sha256:5d4a21e99eada702d3c4c6f0c32e231d876cd76c73da0049d183cd9af5a3057c # {"$imagepolicy": "default:discord-bot:digest"}
              pullPolicy: IfNotPresent
            env:
              - name: LOG_LEVEL
                value: "INFO"
            envFrom:
              - secretRef:
                  name: discord-bot-secrets
            resources:
              requests:
                memory: "96Mi"
                cpu: "10m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
