---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: discord-bot
spec:
  interval: 12h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: discord-bot
spec:
  chartRef:
    kind: OCIRepository
    name: discord-bot
  interval: 1h
  timeout: 1h
  values:
    controllers:
      bot:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image: &image
              repository: registry.gitlab.com/tcordina/discord-bot
              tag: latest
              digest: sha256:1c2ddc6bc1360f2edd2c32ab09de2f985f3ef4bf2e04273a18dcdded82038d03
              pullPolicy: IfNotPresent
            env: &env
              - name: LOG_LEVEL
                value: "INFO"
              - name: POSTGRES_HOST
                valueFrom:
                  secretKeyRef:
                    name: discord-bot-pguser-discord-bot
                    key: host
              - name: POSTGRES_PORT
                valueFrom:
                  secretKeyRef:
                    name: discord-bot-pguser-discord-bot
                    key: port
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: discord-bot-pguser-discord-bot
                    key: user
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: discord-bot-pguser-discord-bot
                    key: password
              - name: POSTGRES_DB
                valueFrom:
                  secretKeyRef:
                    name: discord-bot-pguser-discord-bot
                    key: dbname
            envFrom:
              - secretRef:
                  name: discord-bot-secrets
              - secretRef:
                  name: default-auth-backblaze
            resources:
              requests:
                memory: "96Mi"
                cpu: "10m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        initContainers:
          migrations:
            image: *image
            command: ["python", "-m", "alembic", "upgrade", "head"]
            env: *env
            envFrom:
              - secretRef:
                  name: discord-bot-secrets
            securityContext: *securityContext
