---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: discord-bot
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  interval: 1h
  timeout: 1h
  values:
    controllers:
      bot:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image:
              repository: registry.gitlab.com/tcordina/discord-bot
              tag: latest
              digest: sha256:bce3cd5ce362b2c055bbef9d1d3647e659a3817a2747bd681bb91d5ab9a93629 # @bot
              pullPolicy: IfNotPresent
            env: &env
              - name: LOG_LEVEL
                value: "INFO"
              - name: POSTGRES_HOST
                valueFrom:
                  secretKeyRef:
                    name: discord-bot-pguser-discord-bot
                    key: host
              - name: POSTGRES_PORT
                valueFrom:
                  secretKeyRef:
                    name: discord-bot-pguser-discord-bot
                    key: port
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: discord-bot-pguser-discord-bot
                    key: user
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: discord-bot-pguser-discord-bot
                    key: password
              - name: POSTGRES_DB
                valueFrom:
                  secretKeyRef:
                    name: discord-bot-pguser-discord-bot
                    key: dbname
            envFrom:
              - secretRef:
                  name: discord-bot-secrets
              - secretRef:
                  name: default-auth-backblaze
            resources:
              requests:
                memory: "128Mi"
                cpu: "10m"
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        initContainers:
          migrations:
            image:
              repository: registry.gitlab.com/tcordina/discord-bot
              tag: migrate-latest
              digest: sha256:f49a02fea6b8476f0e0d0c0e90a77eb72363fe6f97cd973773683fc35cb00936 # @migrate
              pullPolicy: IfNotPresent
            command: ["uv", "run", "alembic", "upgrade", "head"]
            env: *env
            envFrom:
              - secretRef:
                  name: discord-bot-secrets
            securityContext: *securityContext
