---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  timeout: 1h
  chartRef:
    kind: OCIRepository
    name: cert-manager
  values:
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
      - --dns01-recursive-nameservers-only
    crds:
      enabled: true
      keep: true
    prometheus:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 64Mi
