---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name alertmanager-telegram-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: *name
  dataFrom:
    - extract:
        key: "monitoring/alertmanager"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name grafana-oidc-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: *name
  dataFrom:
    - extract:
        key: "monitoring/grafana-oidc"
