---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h
  timeout: 1h
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  values:
    crds:
      enabled: true
    cleanPrometheusOperatorObjectNames: true


    grafana:
      envFromSecrets:
        - name: grafana-oidc-secret
      grafana.ini:
        server:
          root_url: "https://grafana.lan.tablar.ovh/"
        auth:
          disable_login_form: false
        auth.generic_oauth:
          verbose_logging: true
          enabled: true
          name: Keycloak
          allow_sign_up: true
          client_id: "${GF_AUTH_GENERIC_OAUTH_CLIENT_ID}"
          client_secret: "${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}"
          scopes: openid email profile
          # auth_url must be accessible from the user's browser
          auth_url: https://auth.lan.tablar.ovh/realms/monitoring/protocol/openid-connect/auth
          # token_url and api_url are server-to-server communications
          token_url: http://keycloak.auth.svc.cluster.local:8080/realms/monitoring/protocol/openid-connect/token
          api_url: http://keycloak.auth.svc.cluster.local:8080/realms/monitoring/protocol/openid-connect/userinfo
          role_attribute_path: "contains(realm_access.roles[*], 'admin') && 'Admin' || 'Viewer'"
          login_attribute_path: preferred_username
          name_attribute_path: name
          email_attribute_path: email
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki-gateway
          access: proxy
          isDefault: false
          jsonData:
            httpHeaderName1: "X-Scope-OrgID"
          secureJsonData:
            httpHeaderValue1: "fake"
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.lan.tablar.ovh
        tls:
          - hosts:
              - grafana.lan.tablar.ovh


    alertmanager:
      config:
        global:
          resolve_timeout: 5m

        route:
          group_by: ['alertname', 'namespace']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: 'null'
          routes:
            # prometheus stack heartbeat
            - match:
                alertname: Watchdog
              receiver: 'null'
            # false positives on k3s
            - match:
                alertname: KubeControllerManagerDown
              receiver: 'null'
            - match:
                alertname: KubeSchedulerDown
              receiver: 'null'
            # - match:
            #     alertname: KubeEtcdDown
            #   receiver: 'null'
            - match:
                alertname: KubeProxyDown
              receiver: 'null'
            # default routes
            - match:
                severity: critical
              receiver: 'telegram'
            - match:
                severity: warning
              receiver: 'telegram'

        receivers:
          - name: 'null'
          - name: 'telegram'
            telegram_configs:
              - bot_token_file: /etc/alertmanager/secrets/alertmanager-telegram-secrets/bot_token
                chat_id: 506962726
                parse_mode: HTML
                message: |
                  {{ range .Alerts }}
                  {{ if eq .Status "firing" }}🔴{{ else }}✅{{ end }} <b>{{ .Status | toUpper }} - {{ .Labels.alertname }}</b>
                  ID: <code>{{ .Fingerprint }}</code>
                  Severity: <b>{{ .Labels.severity | toUpper }}</b>
                  Namespace: {{ .Labels.namespace }}
                  {{ .Annotations.description }}
                  {{ end }}

      alertmanagerSpec:
        secrets:
          - alertmanager-telegram-secrets

      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - alertmanager.lan.tablar.ovh
        tls:
          - hosts:
              - alertmanager.lan.tablar.ovh


    kubeEtcd:
      enabled: true
      endpoints:
        - 10.0.1.11
        - 10.0.1.12
        - 10.0.1.13
      service:
        enabled: true
        port: 2381
        targetPort: 2381
      serviceMonitor:
        scheme: http


    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.lan.tablar.ovh
        tls:
          - hosts:
              - prometheus.lan.tablar.ovh
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        externalPrefixNilUsesHelmValues: false
        scrapeInterval: 30s
        retention: 2d
        retentionSize: "9GiB"
        storageSpec:
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
