validate-kubernetes:
  stage: validate
  variables:
    KUBECONFORM_VERSION: "0.8.0"
    FLUX_VERSION: "2.9.3"
    CACHE_DIR: "/cache/${CI_PROJECT_PATH_SLUG}"
  rules:
    - # ignore changes made by renovate
      if: $CI_COMMIT_TITLE =~ /^chore\(deps\):/
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - .gitlab/validate/*
        - kubernetes/apps/**/*
        - kubernetes/clusters/**/*
        - kubernetes/components/**/*
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - .gitlab/validate/*
        - kubernetes/apps/**/*
        - kubernetes/clusters/**/*
        - kubernetes/components/**/*
  image:
    name: alpine:3
  before_script:
    - apk add --no-cache bash curl
    - bash .gitlab/validate/install-tools.sh
    - export PATH="$PATH:${CACHE_DIR}/bin"
  script:
    - bash .gitlab/validate/kubeconform.sh kubernetes
  tags:
    - selfhosted
