---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sonarr
spec:
  interval: 12h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  chartRef:
    kind: OCIRepository
    name: sonarr
  interval: 1h
  timeout: 1h
  values:
    controllers:
      sonarr:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image:
              repository: linuxserver/sonarr
              tag: 4.0.17
            env:
              SONARR__APP__INSTANCENAME: Sonarr
              SONARR__AUTH__METHOD: External
              SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
              SONARR__LOG__DBENABLED: "False"
              SONARR__LOG__LEVEL: info
              SONARR__SERVER__PORT: &port 8989
              SONARR__UPDATE__BRANCH: develop
            envFrom:
              - secretRef:
                  name: sonarr-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 20m
                memory: 384Mi
              limits:
                memory: 2Gi
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities: { drop: ["ALL"] }

    service:
      app:
        ports:
          http:
            port: *port

    ingress:
      sonarr:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.${DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.${DOMAIN}/oauth2/start?rd=$scheme://$host$request_uri"
          nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User,X-Auth-Request-Email,Authorization"
          nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
        hosts:
          - host: sonarr.${DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: *port
        tls:
          - hosts:
              - sonarr.${DOMAIN}

    persistence:
      config:
        existingClaim: sonarr-config
      media:
        type: nfs
        server: ${NFS_IP}
        path: ${NFS_MOVIES_PATH}
        globalMounts:
          - path: /data/nas-media
            readOnly: false
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
