apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:esuwXPIxoufb5Zdl0MIEN90YF9KL/4I+2jrsPxCS364=,iv:Oj192mQXViKu5WTlOfWdX5MX0NRY/I+qMQSAPlZ5P1I=,tag:Z3Kq9waa4XQe3yK5Ruj3Iw==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSFc5YU5INUtWRDNBQ2or
            a3pBSTFUNU1oUWExb1lMSGxGZ1p4OGZwdUdZCjYrbitBVS9tSVVSM2lGcGxTaERq
            NC9FS29POGZCUjlFbmt6TkNjbmU3ZWMKLS0tIGQxMm9iWjlpQlYxRVBTNWtpQTNs
            L0hnU3BKaG5KbkxGclZENEplMm9tVVUK1glLmqC2fNiL2sn6xrIs2z4aQfmj18/c
            klLHEMKKUuRFWEJ1JHMDEUpHRsnMDbdUtwpu7tiSNA2TDLfIaRw7rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T01:02:27Z"
    mac: ENC[AES256_GCM,data:BpMKh4zpKRz7zgaiLihFlZ2MqV7u7NM+F8zF08lefojb5U+oAEfQ0oTejl40xdQuR+jD9TH8yAbVH5SLXj/wocjO67PBfWQ0dR6pdaqJO5Sh3qrhZP+gd9DAfF2Zp1LR8cg6Q7cQAgDpggYauAZwx8gl1/S3WQVG1t4LqCrtt3U=,iv:ahqtziKrK7hOOeB7rKbPtdvy1Hbziw9uRdzXRlYoLl4=,tag:+fD3h5PmwZFOD/PG1aU1Qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
