apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
type: Opaque
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:LnWn4S+/z89uqk91AJRzk9sr/coPSxwneRZRhHfaug0=,iv:fO0pGwWNVwpQR8HDpYwfuqGQ+upY9zfTUYUSiEW512Q=,tag:U0ybLY9kjjCYfut5U42xyA==,type:str]
sops:
  age:
    - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVlB4clRHY20xaVRTWWRy
        dnJaWVZPaUVkMGxMQ3RsWWdVbEdxTUxjYmx3CnB4RGZzclE2TmxGZWprT3o4VU5m
        d0dlQWthVkd3SmljSTEwcDljcVhnVGcKLS0tIGpvWlRWSHE2THR1V1dJQ0ZxVk0z
        anV6M0cybHJaVkxiczBjelgzcUZKQkkK4Qt4AZnqrfusxkX5FMZxQ+j2rC05/G/Y
        PeSJ13bPsK9xUug/qywSWYXPrU7uIIlkT/V77kp6w2AISe/+WOsqrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T01:02:31Z"
  mac: ENC[AES256_GCM,data:8BjQezd+tBEFlAOVDWCR6TzwqDOpz+t2RT+IbiSP99jZwavU7NNU+zd3fNnnZjV3rvP20mzT6czRgS62O9tc2AS7anPWdF4SZkOKkaEQ0nHWFGtTorSfdZ+bCHjXSa3uKfOs6Sh0+4vNFLj9ftHfhrUZjXBFGcoP/Avtff8+M7w=,iv:pF+S0aWOd5INZAiTcZFiktlXDJ8BRJRFokT42RNHFns=,tag:o6ELm5PuI9GQZSJv99K2OA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
