include:
  - project: "renovate-bot/renovate-runner"
    file: "/templates/renovate.gitlab-ci.yml"

renovate:
  stage: renovate
  rules:
    - if: ($CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_TYPE == "renovate")
