apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./namespace.yaml
  - ./flux-operator/ks.yaml
  - ./flux-instance/ks.yaml
#  - ./image-update-automation/ks.yaml
