apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: gitlab-registry-secret
    namespace: flux-system
data:
    .dockerconfigjson: ENC[AES256_GCM,data:3CxI8ZT9XFWl8PzPGg1AyPRLsKZjFpDOF8TP0lTCWXVcwyeHS188CzZo0P/lRe+OZ73GuoNFT9CwSLQu4GGjgyoAeARixaQipyMrZaEW3M222vF/WKKdfmvcfz3txo8Tl+GdtmpwQNsbA+MuLD8EQsunz6nr8peAuqYgiUlYWLAA9v6aDyVtJA==,iv:K3VoG6pLNk0E03iLHO+XnBD61bSF/ZZ76nUZcfwV8Lw=,tag:x75nihKlprj3YUuBwWHljg==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSk9MNXRZazhTK3VPYkxC
            WkNnUVg4Q2YyVXRrRXA0STVPTmJCYUppMkdVCmhrdkpyc0ZlU3l1c2lyaGU1TElO
            VW9LcWZsZ244OWw2d0NJK1QxRGtpMzAKLS0tIHJsWHhvblhHeFh2WExTYlQ0M3hO
            amRSY2dpbHBjeHE5aEVpeVBtT3AwWW8KzblWcHDJABRKINDdo1Lzhy0EVECc0aan
            Kf8qSUsktAsZ79/Z+c6cF56vBDo4Ia37cy8Kxbkd2gWcie6VZYY83g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T07:46:19Z"
    mac: ENC[AES256_GCM,data:bId2Sbbfej/CQl7ikleSJG4RbHrpgumbkLqkO5jpuEUZpcDhgmLOP9cUqvAnX2BwxikZHp2bgeA188+xbAcrzEASRP/yGVfBeRUkxcJyvvqEftn8zXHnecrCo6OcfPGyXZQ6FAXZQF/JGqell4QC5SHArn51fP9p3mGo6fGUxho=,iv:lxd/KqptxNdKBemmLnzAjlApYZ5ScKR6pzMPN+jrygw=,tag:n1pbJ/bupblY5+BbrH/Saw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
