---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  wait: true

  path: ./kubernetes/apps/longhorn-system/longhorn/app
  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:
    - name: snapshot-controller
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-jobs
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  wait: false

  path: ./kubernetes/apps/longhorn-system/longhorn/jobs
  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:
    - name: longhorn
      namespace: flux-system
