apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: network
spec:
  interval: 1h
  timeout: 1h
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  values:
    deployment:
      replicas: 1
