apiVersion: v1
kind: Namespace
metadata:
  name: dnsmasq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq-deployment
  namespace: dnsmasq
  labels:
    app: dnsmasq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsmasq
  template:
    metadata:
      namespace: dnsmasq
      labels:
        app: dnsmasq
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: dnsmasq
        image: janeczku/go-dnsmasq
        args:
          - --listen=0.0.0.0:5353
          - --default-resolver
          - --enable-search
          - --nameservers=1.1.1.1:53,1.0.0.1:53
          - --ndots=1
          - --fwd-ndots=0
          - --enable-search
          - --stubzones=lab.home/10.43.0.10:53
        env:
        - name: DNSMASQ_VERBOSE
          value: "true"
        ports:
        - containerPort: 5353
          protocol: UDP
          name: dns-udp
        - containerPort: 5353
          protocol: TCP
          name: dns-tcp
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 3Gi