---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab-runner
spec:
  interval: 12h
  url: https://charts.gitlab.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
spec:
  interval: 1h
  timeout: 1h
  chart:
    spec:
      chart: gitlab-runner
      version: 0.91.0
      sourceRef:
        kind: HelmRepository
        name: gitlab-runner
  values:
    image:
      registry: registry.gitlab.com
      image: gitlab-org/gitlab-runner
      tag: alpine-v18.8.0

    gitlabUrl: https://gitlab.com/

    runners:
      tags: "docker, renovate"
      secret: gitlab-runner-secret
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "ubuntu:24.04"

            cpu_request = "500m"
            memory_request = "512Mi"
            memory_limit = "512Mi"

            helper_image = "gitlab/gitlab-runner-helper:x86_64-latest"
            allowed_pull_policies = ["if-not-present", "always", ""]
            poll_timeout = 600

            [runners.kubernetes.pod_annotations]
              "container.apparmor.security.beta.kubernetes.io/build" = "unconfined"

            [runners.kubernetes.build_container_security_context]
              [runners.kubernetes.build_container_security_context.seccomp_profile]
                type = "Unconfined"

            [[runners.kubernetes.volumes.pvc]]
              name = "gitlab-runner-cache"
              mount_path = "/cache"

    resources:
      requests:
        cpu: 10m
        memory: 128Mi
        ephemeral-storage: 256Mi
      limits:
        memory: 128Mi
        ephemeral-storage: 512Mi

    replicas: 1
    concurrent: 3

    rbac:
      create: true
      rules:
        - resources: ["events"]
          verbs: ["list", "watch"]
        - resources: ["namespaces"]
          verbs: ["create", "delete"]
        - resources: ["pods"]
          verbs: ["list", "watch", "create", "delete", "get"]
        - apiGroups: [""]
          resources: ["pods/attach", "pods/exec"]
          verbs: ["get", "create", "patch", "delete"]
        - apiGroups: [""]
          resources: ["pods/log"]
          verbs: ["get", "list"]
        - resources: ["secrets"]
          verbs: ["create", "delete", "get", "update"]
        - resources: ["serviceaccounts"]
          verbs: ["get"]
        - resources: ["services"]
          verbs: ["create", "get"]
