apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-cache
spec:
  accessModes:
    - ReadWriteMany # Allow sharing between pods
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
