apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-secret
type: Opaque
stringData:
    runner-registration-token: ENC[AES256_GCM,data:J/Msu8Q4FvnyPiLWGpcKOb10LjvN9vFiOPG4ySqYcp9Wst0miK+j0v/t4qJ79HOdxTt/5t35Ew8Blez6sPAEOLZUBZ43cXTGyg==,iv:vYMmUpBNqzeXLWfhJKlBRJhGNAYJ/ROqAHHE9+eGXYI=,tag:HpqMQYodSfQqbuLoudzSIA==,type:str]
    #ENC[AES256_GCM,data:jqAeFQiBybr9Pgb8sPxlEa0qcvnXdGI7Cram0f8x6Sg=,iv:yj9HUx59NJgTdq/PmQIMDdfOCjXRpyiYF/8LgdOU6Qc=,tag:YmXH7l0vlyjCX9AL8jAgMg==,type:comment]
    runner-token: ""
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR0JmZDFwYjBDWW5HWmhu
            djBGaTNqa01FTi9HWi92SjlJTnZvMkxIbEVNCmp2bU1vYURrZVVPUFBSQ0tycUVv
            Q1RUbjRuOERyZWVadXNOM0RvbnY0YlkKLS0tIEhVTGZEVnFmZDNjakdxR1lvRG44
            NlRldHB4cVBrem44MHozVVFBcVQ3NU0KGeaXv6tIyqkVF3vQESs9gunQl3oU+oBw
            C0gfZMipABSGnNesIaO8xQpfBjVeikzHGJbNB74dvvv99y3aY5pUvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T00:22:08Z"
    mac: ENC[AES256_GCM,data:i/LbcYobvO6Rrxuj1D0dYqef83PcvZVMD+zmV6C8xwwRSaBW729xr2v6HKJghJR3qBvBmXy2v0Tiz+AL9EEVCgsffU6dm2K7HDe14ngXRcfyjXSgg3GEe6BifJu03WUbWttZMewJU82Z7JRhmtct8gEXY4o6oULzzjP8d9xzv1o=,iv:J9UJxxpzjwzVzksVKJQIJlbqEXgLlgChBKOvuya2Chk=,tag:mZk/MOoffms/fQ9g5msSTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
