apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-credentials
    namespace: cert-manager
stringData:
    applicationKey: ENC[AES256_GCM,data:qDC09GGPzm7aOMcCI2qaeg==,iv:QzweM4xRZzt8TOqX1OZWK2/uGHn+WStUSNZx6W2ouA8=,tag:CZTwjhFW5Fh2zcI9PlPGkg==,type:str]
    applicationSecret: ENC[AES256_GCM,data:NRU4tsmR/J+Lif7Aq1UAUfYNIDWnzhNdj855hrj0+tA=,iv:vJwtnvGxYGgucgm9wxgcNpO842nmK29UKwyfEC8zK2o=,tag:mjseRgo7sootEbi7m3n2BQ==,type:str]
    consumerKey: ENC[AES256_GCM,data:1J67CVg4kljv5TGS26eD49+9nqbB9WXnofMjw/qpM+M=,iv:+u5iJu62nuPvl7Ykl2zq8XsxCh/3c36hZqYAT0Uns7s=,tag:QHj+UwL8oF0bWg4B69CnUA==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Tk9tK1hVU0pCR1d4QzNZ
            TWVRZVhJRzFCbW9DRjZEc1hDRzdsMHhPTFVZClpraHNMMGsrRThzTGo2a2JYL3Zz
            K25wL1Y4VERGdVh4VTNxUkRST25RRUUKLS0tIGZMb1c1NGVnRGJiT25GKzRNc2pr
            czd6dk8wMHNnKzhkcG9CY1NLcGhQelkKhlNocqfTr38WZiElNbjg1SpycvZaCtFZ
            i/vPl6gE0xiyaL6plwjW4eGgoIaAqnf8OtgYXW4Hcx8AWvot3ux1Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T00:37:38Z"
    mac: ENC[AES256_GCM,data:pm3aNyfQdj2DvaC6K8SHQpQJEA8xKAKQUACmojIvquaJfZdWp4ABBlOFU39ZGvN04ChTcSYPaiYBQ6RGvXFoOMsIHx9aYTsrSU3QPQli6Ygvzsta8DSwNJ/PSIq5of4heUv6KVenQTQhERwtINXXSgqRMsyK7PLML+7Ygz8IB4s=,iv:CZNbnMrmtNgMB8Ad+cusUC4eBi3Aza+348gtsiOhOXQ=,tag:kFcg70aAaR5iX5VLc4t0yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
