apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ddW7Wuvy3HZXXQbU3bgNRK6/p3BmeO0D1oAV/80tnwwPYl+FzJtRpg==,iv:iObhoqxWCAbMTh/2akA2IjvYQ8yCsBc4RrfirTCrGd4=,tag:HJhmOQoljHhRBC09P0xJbA==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoamQ3OTlmbzRnazhwNitl
            UDhLbkpOL0NYb1pyUGFRMjBHS3N2UTVnTjEwCk13T1Q2U0VsbEpDRUg2NGUzYmcz
            MDNsYWFYNmZiZTFkL2JBV2RjRUdiaDAKLS0tIDExZkpqWGNSbThVa3ZXWmFiRVds
            WTh0bEVjd3JraHpwVDRSK1lLSnZGOEUKtNWbz69p26y8AL97Cvi/KWdFEK9XiMtl
            fGnUCaga4u1ft4FtwML1HyvHYp5i/bU3W0u3FEsQvqfnSBsoMVfC1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T01:02:33Z"
    mac: ENC[AES256_GCM,data:3VphgMq0UZRDxK8KDOHafFkI8ccGbii1Y+bqEvmP5hdz2/Pu0UiaKfFDKvbd3PlWFLVcEO2yduRbdOOriZwNDK0x/AMyxGQYUZgbbkY2msRAyPnpW2zg/0bJLqf8KAms1uWZ9cK+ErTpDoviSzV46FERlp7nqYDVtlsV9thagCU=,iv:T5iZK/9m7+9+bZZ58yHBntoOJDTJ9O662H5JETvuwqg=,tag:Vv5mpfHfXujHfgEKjDOpOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
