apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ejlHixUsoYviOdJTAwr5pXi5tcfV+NWhg50QyhKlP+3lAdnqb4jfXw==,iv:qdFVSQj2PWWTfqX0mu1wU2MJKaOKnOdtyR3YCEe2VRI=,tag:Yes1LF+MR9TTj1IGw32W7Q==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOWNqR1FVM2pzamduRjN4
            SS9HQUlRcDVIVTU3THZNNDdhREF5cVM1VGlVCmN0cEtUK0VpeXVEY3doRStmVGJj
            elNZTStVOUoyS2Vhc0lyaEZsdEdjcmcKLS0tIEF2YVBsemFhNjdkOWhMV2NQbk92
            cXJjSGgya2wzcUdhbldyMWU2NWtOVGsKtC0LMAijksGo42U582kB4Un0zq3+roiM
            yUqQ8UL19W6QfDGbH96drWnQNeirSq9yWa5wQFmlQYGAmHN0YcZCUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T02:51:56Z"
    mac: ENC[AES256_GCM,data:KisiRkWgEtFMbBnn8IdTxu4dxBrdzeoye8pX5vuzFZUXPnoaS26pnL/57utAdcUdKHM9tJkOQJ+OmMZPxHOk2Xs97uw4YSST4tMXUu26oW9mto81hESjwE70Np+fplb6iLi4ZBJmjGHl9Awu1uPJ4JF9pu/etEYVCXiQxxbFP24=,iv:8C3OtpKuHf5Qd+K5VAVgrCQNj4VnUHw5giA5kZFpSzM=,tag:XWXFlYkz4M/y3yil8FFeDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
