apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./auth
  - ./cert-manager
  - ./database
  - ./default
  - ./external-secrets
  - ./flux-system
  - ./network
  - ./kube-system
  - ./monitoring
  - ./multimedia
  - ./storage-system
  - ./test
