apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: oauth2-proxy-buffer
  namespace: auth
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: oauth2-proxy
  connection:
    bufferLimit: "64Ki"
