apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: radarr-buffer
  namespace: multimedia
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: radarr
  connection:
    bufferLimit: "64Ki"
