apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
type: Opaque
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:ziMsbEIEJbEF3VZuG32D4iBfw7SjuJTdL04w5E0LjCk=,iv:nlPUkevk1HBvtV9B256Ar0ywiTNYRBSOAv/MiBuojrk=,tag:J4kLxEGCNEi6sGYntg9s/g==,type:str]
sops:
  age:
    - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMmVOTElXcWdrc0x2Zkhn
        cWFZc2tBN3AwRHpJZlBBUnhRaWZIZ29Xa0ZRCjZNVHA5c2thQXpZYlFEakNPQnYr
        U3h5WmpEM1VBWUk1dnFmaXhYSkhWMGMKLS0tIHg5a0Rmb2lLb2NCMDZiMVRBL1E3
        VUUwdm5KT2RJSlJKaU1mM1o1THpZYVEKTqp5JuC8VemLyCz9M3xa5Ih1VYPk3Ymk
        14IUtk4T746IpFPyO5iUJ8euCpucnBLxt40VakaE5pfd8Xlh2iA/Xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T01:02:23Z"
  mac: ENC[AES256_GCM,data:umnDy1dVBr4x6oyY0DJNfXPVsB7BXhasvoSnsOETNKkT7y6dkczBw4fFmseZaxT+jRSjEcGE864n7s7bEtczHuMKnWmNLXmyYd13E3ewJN8hYN/AKVMTDRrB68Yja8INpKTpbltgbXIw7ayW6u96jKFf5PXC1pqxM4IVcHzvvFc=,iv:Y9p9xFz9KGhHCFYiNxiMRO0qE3gT/e7efe82d0W0ooc=,tag:1Khq5J24yWEtJr7N25bNEQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
