apiVersion: v1
kind: Namespace
metadata:
  name: discord-bot
---
apiVersion: apps/v1
kind: Deployment # TODO : use helm release instead
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: registry.gitlab.com/tcordina/discord-bot:latest@sha256:6b15fa53933f5d60ad6e0df3fbb7aca62166bf135f3627d004901186ae00a45d # {"$imagepolicy": "flux-system:discord-bot"}
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "INFO"
          envFrom:
            - secretRef:
                name: discord-bot-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
