apiVersion: v1
kind: Namespace
metadata:
  name: discord-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: registry.gitlab.com/tcordina/discord-bot:latest@sha256:4c67e8ab6d4651947a20c059468cb15baec7a2fc3dd56e510e04a2d8d6fbfd92 # {"$imagepolicy": "flux-system:discord-bot"}
          imagePullPolicy: IfNotPresent
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secrets
                  key: discord-token
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secrets
                  key: hcloud-token
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
