apiVersion: v1
kind: Secret
metadata:
    name: discord-bot-secrets
    namespace: discord-bot
type: Opaque
stringData:
    discord-token: ENC[AES256_GCM,data:xxg7pfMNGqBInBjccr/DKmSHa2IJiEUQyvzP9nDcda1OS9xItVCe3f6cT2viufKZCA5+c3DIdWlpi6aWkN/sXeXPb4nVyBod,iv:5pkFzC90zvny4InDwKiAuWtEPbjbfMIaUdA+sLEYIN8=,tag:oYnGMO3h2Cmz9CEKdg9vLw==,type:str]
    hcloud-token: ENC[AES256_GCM,data:yYsA1eKYZD8Sp/1d9PbmPBRabWEjWxsSsg7f1DTl7ZrR1eKp6cVN1TPSVj2VF8vlYBI4U//Li1rAv7Pbq22q9Q==,iv:NPc16+PFGT9Ez5Yt9eUHMUxmQYhEwBjE/Da2mbF10zo=,tag:ws7YA0LC8l9M+/IScTA0IA==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWci93cmJnTFBSREJjRDFx
            YnB3SFJLSG9Tb1ZrTS80TGJmeU5HOEVNVkNBCmxudlA5ZE9SVkFqOWlycDFNbU12
            NEhUN0ZhT2tONkx2bS8xMDgwUEhsdDAKLS0tIEVuajI1MEQrVzhnbURyT3U5bG1r
            eVptWUl5M3BqZENESWhTdWRNYVFXSXMKBdHQNFqJM+w+KZRrGg2ezvDbagKk6Akf
            ohrPS1/IUuuR3nLax9awrMdWGiPJD8u2gReda9/59TndfRoWiJD7og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T07:46:19Z"
    mac: ENC[AES256_GCM,data:T5oGmlG7ow93miLIMvT0/9no3CwPuqp/K/TRKBtGKVrTOnh5lcSPKSE4f3UNWxsri79zrSMydi41VaUHvts+frnXEm09QUZwJX9IYaamK4BUKyYQWuZ7/9vTPGrmn22NSnISCTt61tjqrH8mY+AEhBQakmTjhksj0D4WDqjWMXU=,iv:++vaTxVnW+XjwgvwasK6Vm6kemegumU5ouvEiN0SFzE=,tag:kQTPrUJdQFzr1mb8wjNCng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
