apiVersion: v1
kind: Secret
metadata:
    name: discord-bot-secrets
    namespace: discord-bot
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:xv/sbhHk1oFygNpa1zEODrEZxnzMCTsPpyvfOcxV5C9eiwb21L+FVe+w3klH31k4/u0mLKYRV1b2E9IDe07Ewk89B9ZwzH5r,iv:97z8b6+tYxCkN/kntC56BxE3esjv78V41wLlc1UsJ1k=,tag:oxbd8Mc0DI9itb0EwFlSHQ==,type:str]
    HCLOUD_TOKEN: ENC[AES256_GCM,data:tkz7R+vVGcsxzUbMyqrcbqw/NnqBISQypZdNYHoG9m51rHTEbm6QMsK8wRBQFVBvhzMoB12IX/vAD2j1lvZGbg==,iv:77ifOnG2pOjnbNy9Ggife+9ZmYqBPViY92RyxZVtEFk=,tag:69/NwJmXAldjlue3dlZA/A==,type:str]
    RCLONE_B2_ACCOUNT: ENC[AES256_GCM,data:Eu8eiuW4f8Jku1zXq1Q3BU48703Q2yFxBA==,iv:u/FVWoCNRoG+DmHkaBerk/6xZdEJk4yjI2SDBe/B8LI=,tag:Lu2ldNgUCcbB3EInmxBNWg==,type:str]
    RCLONE_B2_KEY: ENC[AES256_GCM,data:ub6KAOCUAN+rnWx1D9TdWzzHv+KnyqT6jQWpbhMHWw==,iv:7JdCg5nPh0GkPWx/NSPuBA5JaZDScRdfF8BR2JmIWEA=,tag:T0mMRRVU/5WppfGa5xM0NA==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQXlJeCtwajB0NnNYNFJm
            azFUZjhORDU2UUxWWllKYUhCK0w5QnArYzM4CkxrSCtuNjh5WVZ4LytPU2ZOZEdt
            K3lDVGRWMnJXYXdkd3NURWtwcUhYWVkKLS0tIHBaT204UFFWUkM5RkdEOGtXRFpU
            UEMwUWpSMC9XZHRyTDczS2czZnMyZmMKIP0OD2awQnO0CvOrBVDtRbdH1KfqIciP
            HwMBbDx/GAVW9Wkkp8ADBbZxdD1IhhBZJG40XWEqphg1ImerXJdSUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T18:44:29Z"
    mac: ENC[AES256_GCM,data:U9j2Ixkg6FVkz9sUC2u+DsbFIrq/Y7hGSmxvTOQU3xuqPnQZnRMgFXP5kwqtifKHCa1ulmWSNnyIhv8USXzfnNFG2yRuBDk0x+qGKQnBqoyk07ZbzG5VWu8ZxHYMbiu9g/J+8byIZqUWpV3l3eOjuWy4R2FJ36GevGPsBwx/uYc=,iv:B3tyHT1bAy9F2OOrFfiScwHwP2GMRTtw9wPe0JXEmpY=,tag:3rYMM2df9/AmyVmOpRlQmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
