apiVersion: v1
kind: Secret
metadata:
    name: discord-bot-secrets
    namespace: discord-bot
type: Opaque
stringData:
    discord-token: ENC[AES256_GCM,data:1znvbmiRGxuRwAWLVX7kfxyuNOuMDdJ7MGyuqmkNSD+3ArCHwiD8BYnlvKxE+s4s18NYoZAJ9bXzvwFIBuxklw9QTVL9Fq4U,iv:qtmyVlFIqqQDDn+SdjMPKXFai7P4BzOwPrUZ6y8jXYQ=,tag:W5sw5m3ySIKd/h34UOg+Fw==,type:str]
    hcloud-token: ENC[AES256_GCM,data:BWBJVnDEwoIeRhNkRdg7dzEve4yuO/xgYde/TV64AlfFEiP2J6rxe7/xHBHnQezEzEH+X1SGcU4MoIzJ2QTt/g==,iv:F+BgFwOvHqVKQq7RNb7359Vwxpavn6QBrgmYBXH2hSc=,tag:AHLGVev97CKgIF9eKu1nOA==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TnFxSkxaNzRFbEVlTGl5
            UTFqK0lSQXo1T0F0eUZEYkFINmFJR3g4K0J3CnNYcU9HOUNOL3VGb1QydFJHemZ3
            Y3hiRFVqcFpGNjB4Wko3eUlMMklMcDAKLS0tIFVyaWNMMkFFc2s0bm1VbTEwSG43
            elBlOHU1R09XaTlnVjY3cVhmTjFIbUkKL6VaSa0QTRE45E7yjJ3Tt5mC6NRua3Uv
            9W4KknZQFtViGxQa+w1o2SgMWyaZgolLiPQrgJuiV3v7ZfJxZ6UKeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T11:19:38Z"
    mac: ENC[AES256_GCM,data:OJJsnFEbVilU9diPDI6t/6irTqgB0mTxNa970x7S/ZqqXhhETo4RWv/beO+EYY3H5JANeehnZ+AZDy0/93kcNSHpd1wXlnZa5N25hUweabGsM8Kkq8Z9tEwQSoGf0FdPb47l41oMjRgl+JRFGcmxg1LLVv/AvQVVX/8JztSlq3I=,iv:8UmoyfBP/bYnZYQUlobe44pkUA7l/36e41l+TtfNuPM=,tag:WfIdvv6g1ot3cjF40bmdDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: gitlab-registry-secret
    namespace: discord-bot
data:
    .dockerconfigjson: ENC[AES256_GCM,data:pmWZBc3NjU3SOi+eNYLQPfYO8UD+7kzXEQS0+eUXogSoyB9PoVsAb9HuGBmUph1U1m66gdddx3glJ7+xJYTCqTh1fC1QfrCCCeGbbyQf12AWrTOnFFKBRTVIbS8gmQDoQdRP8WMa46jSBZmJdiOWJO1reiTgN7KCAC9Qbb/ObIjvalOntke7vQ==,iv:7uEAuj3ptSZqQyRNj3bZXB7PVSpZWCFtBzR4VuVE61E=,tag:fXdgkuEVhwLho6qt6hurCA==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TnFxSkxaNzRFbEVlTGl5
            UTFqK0lSQXo1T0F0eUZEYkFINmFJR3g4K0J3CnNYcU9HOUNOL3VGb1QydFJHemZ3
            Y3hiRFVqcFpGNjB4Wko3eUlMMklMcDAKLS0tIFVyaWNMMkFFc2s0bm1VbTEwSG43
            elBlOHU1R09XaTlnVjY3cVhmTjFIbUkKL6VaSa0QTRE45E7yjJ3Tt5mC6NRua3Uv
            9W4KknZQFtViGxQa+w1o2SgMWyaZgolLiPQrgJuiV3v7ZfJxZ6UKeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T11:19:38Z"
    mac: ENC[AES256_GCM,data:OJJsnFEbVilU9diPDI6t/6irTqgB0mTxNa970x7S/ZqqXhhETo4RWv/beO+EYY3H5JANeehnZ+AZDy0/93kcNSHpd1wXlnZa5N25hUweabGsM8Kkq8Z9tEwQSoGf0FdPb47l41oMjRgl+JRFGcmxg1LLVv/AvQVVX/8JztSlq3I=,iv:8UmoyfBP/bYnZYQUlobe44pkUA7l/36e41l+TtfNuPM=,tag:WfIdvv6g1ot3cjF40bmdDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
