---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: &name fs-trim
spec:
  name: *name
  cron: "0 5 * * *" # every day at 5AM
  task: filesystem-trim
  concurrency: 1
  groups:
    - maintenance
