---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1h
  url: "https://gitlab.com/tcordina/homelab-cluster.git"
  ref:
    name: refs/heads/main
  secretRef:
    name: flux-system
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
