apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &service-name nextcloud-postgres
spec:
  serviceName: *service-name
  replicas: 1
  selector:
    matchLabels:
      app: *service-name
  template:
    metadata:
      labels:
        app: *service-name
    spec:
      containers:
        - name: *service-name
          image: tensorchord/pgvecto-rs:pg16-v0.3.0
          env:
            # Store data in a subdir. Using a mount point directly as the data directory crashes the container
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: nextcloud
          envFrom:
            # sets POSTGRES_USER and POSTGRES_PASSWORD
            - secretRef:
                name: nextcloud-postgres-auth
          args:
            - -c
            - logging_collector=off
            - -c
            - log_destination=stderr
            - -c
            - log_statement=all
            - -c
            - log_duration=on
            - -c
            - log_line_prefix=%m [%p] %q%u@%d 
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: nfs-csi
        resources:
          requests:
            storage: 5Gi