apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-postgres-auth
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ax7r+3kFW6Cr,iv:EQDZgzo4N1rjhDC7knJwymIibH3MGX+2vwpHkUPoWf8=,tag:m1F90P0mW6ip0itPen0mQw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vIXjmX5fR5N5,iv:jtsoZniK0DB8mDPkpcmfxkOrXHJILNcp3trVoamnnB8=,tag:5kCeJqbbRb5zdO6aNp8kbg==,type:str]
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSkgrZXNGTDVxRjlqaWJK
            aG9KdFFlS2h3Q3VlNWNaUkV6cHdoV3cxZ2xBCmdLb2c5QVlSWFNpeURqSTlwSy96
            L2laUDI3NU1hYkdPcHdIR0xCQUtrdjAKLS0tIG9tRnpHVE44V1U2c2FPSEliNnhG
            dUJ6cjVGdGhZenRpeGEzQzNuSWV3WU0K2+eSaYc812UjJbOnrRTqR5KzI69/OvcB
            35KhPMsXa9QyRs8bgN6mCNIMgGUQdWy4WG+k4crB77kg38SfPrzshQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T22:46:46Z"
    mac: ENC[AES256_GCM,data:5LucDgpg/A8LroSzkHYejduWZ16gMhwn4eYkI5Bxft/Mv0ztSRw8tEGjse2uYdPSBZOyv+tkRPtBtXPV2KWLMgVQ9eBMNq/qWiVLLimLrxN4EwoHgOL7EKxc0217qTUTpGVagyGbMr7MR9gqOPg3C261uLjuvlRi4xh03zG1dmw=,iv:eJVdrUWpiAp9DzfXUtjWtdYsVo02RfMCHMmDLHdFxbM=,tag:ROhlmRkl20Ngbgvt7QRAhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
