apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-cache
  namespace: gitlab-runner
spec:
  accessModes:
    - ReadWriteMany # Allow sharing between pods
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 10Gi