apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-secret
    namespace: gitlab-runner
type: Opaque
stringData:
    runner-registration-token: ENC[AES256_GCM,data:1F8Qg4EuK675JhS/vK1frh7GKwc5/HRPnP3FHJe6hb+AYNkdxZmtaHe+ZQmjskWbsFNImOPwcMBBvr6gol4rUcFXMTKDijFxfQ==,iv:vBgK2fFf02S3z1uaAMVrmp8ATdtZ9lVvmcY1wNgXUEQ=,tag:GhEC0USmmJDajQLmDaMdYg==,type:str]
    #ENC[AES256_GCM,data:cotQRLNNhB2P8fuOZpN69yACEJGtBDlebs8/Gd/Gj3E=,iv:yMDu0myJBkGzHGBcN5DJ90NC2LmAAPRzkAtz+/cWyAg=,tag:7rUc9zNAvVyNann3n6R+dg==,type:comment]
    runner-token: ""
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndWJubzk3dWdKeHB1Vm81
            cnVqMGl1MDFqdm0zMDExWm1TTUZqTDFNQ2k0CmgyVWtsbGRvVXJRNERNNG8wVGFB
            cVZMbTNUOVdac3lkdDEzV2o2SGJMVDAKLS0tIG5neWdibmQwQzdFUkpYUlQ3Ti8y
            a2lsMkc4cXhHOEtuTDhuNldIbWVudlkKegkrimOemuApLkSXRtWHobxf20ZW1Pnq
            zSqug+smgjBtnWJwEhOKoULCT8ZEj7xCSCx88fZsThUlC39Zw9lMDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T15:40:03Z"
    mac: ENC[AES256_GCM,data:3PJGuFOZmdFv5K/x9aHKxrlgdiZg0V5U9qoMGVXDbQ941KSMBfaMv1tBbtegDqVDhDoryrZISlkfGMLOYzDmXMuj8uqMB0cI2VjvLyG8cUjS+sdds0aR8ObxfAlkZI4h+Mj22RMswj1P5ayiTskSe/Ge3XbhY+jIJyKwqIbzQ70=,iv:mlEkSQPAm//gXcTDc42i2oKuaBz/Yx5bAmaeB4+XKJU=,tag:cwnAVr6L4WkOPIx//05YiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
