apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-secret
    namespace: gitlab-runner
type: Opaque
stringData:
    runner-registration-token: ENC[AES256_GCM,data:so/KNxw67BSxholwyKBXJbVTsgYlpvchzp+ISGCRjzphC6w4VOcV4HV08t6kSG00c1ZqyllXqDEnG780BOBwgXriZl4hLV6AHg==,iv:8FFsMvEUsu5MN5mfhkgCv6R69pWtueFPLjAao9P6/30=,tag:MRfKIhTUwKAk6ERk/ykvEw==,type:str]
    #ENC[AES256_GCM,data:Zi6HP8ibiFklnL/NpaCagPSxe9eexqgSeLjEBE4m0EM=,iv:rFYdaTOlEdk26hyUA+vP7U41jsg3sNZF55sYOqRUNIA=,tag:QgdQAIPCaS8u/Sa+uVyJTw==,type:comment]
    runner-token: ""
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdTdyaVVCd2NCZm1IcWJM
            YWRoR3lHVlZEb3B1RDNVbW5neUZvNmpJcmo0CjRXR0hleVlLOHRrRmJuN3dPS05K
            d3RkUEc4SUV5VG8yYS9QYzcxMEZCL2cKLS0tIE5GVE90RE1CbWF0VWlpM3FhZTU3
            Z1I3K01DbW1MZnRyVStlejJNVkpnSm8KAwERcs4l92SPfmmsO2Upk2LF+PMFvvu+
            MvoZMcTzYxvtvFMsh+2U4/1wyxN2OeZcyL6cSlo18xVZuhqWYiFBYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T07:46:19Z"
    mac: ENC[AES256_GCM,data:gAHjbmd8spsSVad5Bvxd62i3a5V/z/RIvy86IeMLfefAgKGnIWaaxormaWjj8d/AhWWLyLz27PmrnuLeoHj5cw3spVJw7t+ZJR8u4Rtpu5jKWFgvHTXVVm6bvtWf/DQZAE9TW7zDTy3l1OyoHahXieyM/7dG0ik8PNkvhN5tOuY=,iv:mF8Z/CX95Pk9+aifHxVj3R43VbA6QkPnxOytp4k0nDU=,tag:vlaNoycwIs1MBGK89+p8Qg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
