apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-secret
    namespace: gitlab-runner
type: Opaque
stringData:
    runner-registration-token: ENC[AES256_GCM,data:GB80X5+jS6vrbgc3oFr5/PQP/qIZgvlSyQ43s8grS6C4MykJjgpObsF5PdLVrV+O2DIMAYFZh5wOxh/iNQfSM3Cu60iOmjhMrQ==,iv:baIVVtFvknEm7As7hsw3CiyD2Lg0/P0lsYPriBpGZDE=,tag:2JcjQQTd8mXeWgyGJ4Iu3w==,type:str]
    #ENC[AES256_GCM,data:P80I8xyVBuGA1I/Cx8W45EyeosCDZjyOU+fw99LOu6A=,iv:pze/kKi1XL19gyMyOVOCWKwGV7PmGyG6Vep7SkGEgJk=,tag:2LcL5+gVm/cIKPxpvTFsfw==,type:comment]
    runner-token: ""
sops:
    age:
        - recipient: age15hze00etfjf5mgj068wdjduhtpthwj6n72z5zn2m639sxelc340s9x68pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOEk0VDBGU2w5dkYvU0sr
            ekFaYlhLTVVMWnFYdGJtTnBKWjBxTHo2ZEdrCnE0SlF5VXV6QjFZQTByb0pDY1Zq
            UmtmQkkzMDFnV0VZYzJacTVuTUg0N3cKLS0tIEd5SFJKRzA0Lzl4elVFNUN5czRt
            VGRuR1d3U0hTU2dMQzN4UkNOL0FHWkEKR5Tb8o48kMIjuKGB+E7NZqjJrg6gB9l4
            gU1RtY+WWnq9aG8Sie1Fxn4DU0Ky3SOClnj0pMI8tgDOO7F4XshROw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T09:43:20Z"
    mac: ENC[AES256_GCM,data:KD1PmrFjwp7CaTs+opFnfsQbp1gfMwHHJTZF9mCXlqU/5E3BjG5G//sby6ncerfcj/xuSkyp641bAefDm3OWeCwEeK505KXFTBJmRzVw7mPojK7hdmUoFznx0dc/jik6aIvy+zRLEb2U/vCnqK4k5zZb1ZJnPq7PU+CPE93pN18=,iv:fioPG4DbhMrrgcM7dkrHFanYO/xMHWblVdUVMniHRXI=,tag:z3po/gczU9AF6GvgIK6APA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
